require 'descriptive_statistics/number.rb'
require 'descriptive_statistics/sum.rb'
require 'descriptive_statistics/mean.rb'
require 'descriptive_statistics/median.rb'
require 'descriptive_statistics/variance.rb'
require 'descriptive_statistics/standard_deviation.rb'
require 'descriptive_statistics/percentile.rb'
