require 'descriptive_statistics/support/convert'
require 'descriptive_statistics/number'
require 'descriptive_statistics/sum'
require 'descriptive_statistics/mean'
require 'descriptive_statistics/median'
require 'descriptive_statistics/mode'
require 'descriptive_statistics/variance'
require 'descriptive_statistics/standard_deviation'
require 'descriptive_statistics/percentile'
require 'descriptive_statistics/percentile_rank'
require 'descriptive_statistics/range'
require 'descriptive_statistics/descriptive_statistics'
require 'descriptive_statistics/stats'
require 'descriptive_statistics/class_methods'

